DROP TABLE IF EXISTS users, posts;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  profile TEXT NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE posts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users NOT NULL,
  photo TEXT NOT NULL,
  caption TEXT NOT NULL,
  tags JSONB
);
